apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../charts/user-service/templates/deployment.yaml
  - ../../charts/user-service/templates/service.yaml

namePrefix: prod-

commonLabels:
  environment: prod

patches:
  - target:
      kind: Deployment
      name: user-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: user-service:prod
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
