apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../charts/api-gateway/templates/deployment.yaml
  - ../../charts/api-gateway/templates/service.yaml

namePrefix: dev-

commonLabels:
  environment: dev

patches:
  - target:
      kind: Deployment
      name: api-gateway
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: api-gateway:dev
